import { describe, expect, it } from "vitest";
import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { ALL_FORMATS, BufferSource, EncodedPacketSink, Input } from "mediabunny";
import { sampleAt } from "../scripts/gen-alac-corpus.mjs";

// The exact oracle.
//
// ALAC is lossless, so there is no "close enough" here: every sample the decoder produces
// must equal the sample the corpus generator put in, for every channel of every fixture. A
// scaling slip, a wrong bit depth or a channel swap all fail loudly instead of sounding
// approximately right.
//
// The corpus is generated by scripts/gen-alac-corpus.mjs and its integrity is checked
// separately by scripts/check-alac-corpus.mjs (which uses a decoder we did not write). Here
// the fixtures are decoded by OUR wasm, through the fork's ALAC demuxing.

const CORPUS = join(__dirname, "../test-corpus/alac");
const WASM = join(__dirname, "../alac/dist/alac.mjs");
const ready = existsSync(join(CORPUS, "manifest.json")) && existsSync(WASM);

type Fixture = {
  file: string; name: string; channels: number; rate: number; bits: number;
  frames: number; freqs: number[];
};

const manifest: Fixture[] = ready
  ? (JSON.parse(readFileSync(join(CORPUS, "manifest.json"), "utf8")) as Fixture[])
  : [];

/** Decode one fixture to per-channel integer arrays, in the decoder's own channel order. */
async function decode(fx: Fixture): Promise<Int32Array[]> {
  const { default: createAlacModule } = (await import(WASM)) as {
    default: (opts?: Record<string, unknown>) => Promise<any>;
  };
  // The shipped build targets web and worker, so its glue fetches the .wasm by URL. In
  // node there is nothing to fetch from, so hand it the bytes directly rather than widening
  // the production build just to make a test run.
  const wasmBinary = new Uint8Array(readFileSync(join(__dirname, "../alac/dist/alac.wasm")));
  const mod = await createAlacModule({ wasmBinary });

  const bytes = new Uint8Array(readFileSync(join(CORPUS, fx.file)));
  const input = new Input({ formats: ALL_FORMATS, source: new BufferSource(bytes) });
  const track = (await input.getPrimaryAudioTrack())!;
  const config = await track.getDecoderConfig();
  const cookie = new Uint8Array(config!.description as ArrayBuffer);

  // Hand the cookie to the decoder through wasm memory.
  const cookiePtr = mod._malloc(cookie.byteLength);
  mod.HEAPU8.set(cookie, cookiePtr);
  const ctx = mod._alac_create(cookiePtr, cookie.byteLength);
  mod._free(cookiePtr);
  expect(ctx, `${fx.file}: decoder refused the magic cookie`).not.toBe(0);

  const channels = mod._alac_channels(ctx);
  const bitDepth = mod._alac_bit_depth(ctx);
  const frameLength = mod._alac_frame_length(ctx);
  expect(channels).toBe(fx.channels);
  expect(bitDepth).toBe(fx.bits);
  expect(mod._alac_sample_rate(ctx)).toBe(fx.rate);

  const bytesPerFrame = mod._alac_bytes_per_frame(ctx);
  const outPtr = mod._malloc(bytesPerFrame * frameLength);
  const out: Int32Array[] = Array.from({ length: channels }, () => new Int32Array(fx.frames));

  let written = 0;
  const sink = new EncodedPacketSink(track);
  for await (const packet of sink.packets()) {
    const pktPtr = mod._malloc(packet.data.byteLength);
    mod.HEAPU8.set(packet.data, pktPtr);
    const frames = mod._alac_decode(ctx, pktPtr, packet.data.byteLength, outPtr, frameLength);
    mod._free(pktPtr);
    expect(frames, `${fx.file}: decode failed`).toBeGreaterThan(0);

    // Deinterleave. 16-bit is int16; 24-bit is PACKED three bytes, not a 32-bit container,
    // which is the single easiest thing to get wrong here.
    for (let f = 0; f < frames && written + f < fx.frames; f++) {
      for (let c = 0; c < channels; c++) {
        const at = outPtr + (f * channels + c) * (bitDepth === 16 ? 2 : 3);
        out[c][written + f] = bitDepth === 16
          ? (mod.HEAPU8[at] | (mod.HEAPU8[at + 1] << 8)) << 16 >> 16
          : (mod.HEAPU8[at] | (mod.HEAPU8[at + 1] << 8) | (mod.HEAPU8[at + 2] << 24 >> 8));
      }
    }
    written += frames;
  }

  mod._free(outPtr);
  mod._alac_destroy(ctx);
  expect(written, `${fx.file}: frame count`).toBeGreaterThanOrEqual(fx.frames);
  return out;
}

describe.skipIf(!ready)("ALAC decoder", () => {
  for (const fx of manifest) {
    it(`decodes ${fx.file} sample-exactly`, async () => {
      const channels = await decode(fx);

      // Which source tone did each decoded channel carry? Discovered rather than assumed,
      // because ALAC does not use WAV channel order: each channel of the corpus has its own
      // frequency, so exactly one source tone must match each decoded channel exactly, and
      // each must be claimed once. That checks losslessness and the ordering together.
      const claimed = new Set<number>();
      for (let c = 0; c < channels.length; c++) {
        const matches = fx.freqs
          .map((freq, i) => {
            for (let f = 0; f < fx.frames; f++) {
              if (channels[c][f] !== sampleAt(freq, f, fx.rate, fx.bits)) return -1;
            }
            return i;
          })
          .filter((i) => i >= 0);

        expect(matches.length, `${fx.file} channel ${c}: matched ${matches.length} source tones exactly (expected 1)`).toBe(1);
        expect(claimed.has(matches[0]), `${fx.file}: source channel ${matches[0]} claimed twice`).toBe(false);
        claimed.add(matches[0]);
      }
      expect(claimed.size).toBe(fx.channels);
    }, 30_000);
  }
});
